---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.9.0에는 몇 가지 새로운 기능과 향상된 기능이 포함되어 있습니다. 
---
= Cloud Volumes ONTAP 9.0의 새로운 기능
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.9.0에는 몇 가지 새로운 기능과 향상된 기능이 포함되어 있습니다.

최신 버전의 BlueXP에는 추가 기능 및 향상된 기능이 도입되었습니다. 를 참조하십시오 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["BlueXP 릴리스 정보"^] 를 참조하십시오.



== 최신 업데이트 (2021년 4월 21일)

AWS에서는 DR(재해 복구)을 위해 최대 24개의 SVM(스토리지 VM)을 구성할 수 있습니다. 이전 제한은 DR에 사용되는 스토리지 VM 12개였습니다.

link:reference-limits-aws.html#storage-vm-limits["스토리지 VM 제한에 대해 자세히 알아보십시오"].



== 최신 업데이트(2021년 4월 12일)

Cloud Volumes ONTAP 9.0이 출시된 이후 몇 가지 업데이트가 있었습니다.

* AWS 업데이트 *

* Cloud Volumes ONTAP는 이제 9.7 릴리즈부터 GP3(General Purpose SSD) 디스크를 지원합니다. GP3 디스크는 광범위한 워크로드에 대한 비용과 성능의 균형을 맞추는 가장 경제적인 SSD입니다.
+
https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-planning-your-config.html#sizing-your-system-in-aws["Cloud Volumes ONTAP에서 GP3 디스크를 사용하는 방법에 대해 자세히 알아보십시오"^].

* Cloud Volumes ONTAP는 더 이상 콜드 HDD(SC1) 디스크를 지원하지 않습니다.


이러한 EBS 디스크 변경 사항은 BlueXP 3.9.5의 일부로 도입되었습니다.

* Azure 업데이트 *

* 새로운 E 시리즈 VM 유형 지원:
+
** PAYGO Explore 또는 BYOL을 사용하는 단일 노드 시스템의 E4s_v3
** PAYGO Standard 또는 BYOL을 사용하는 단일 노드 시스템을 사용하는 E8s_v3 및 PAYGO Premium 또는 BYOL을 사용하는 HA 쌍
** PAYGO Premium 또는 BYOL을 사용하는 단일 노드 시스템을 사용하는 E64is_v3


* Cloud Volumes ONTAP BYOL에서는 최대 24개의 SVM(스토리지 VM) 지원 이러한 24개의 스토리지 VM은 데이터를 제공하거나 DR(재해 복구)에 맞게 구성할 수 있습니다.
+
9.9.0 릴리즈에서의 이전 제한은 Azure에서 DR에 사용되는 스토리지 VM 12개였습니다.





== 9.9.0 GA(2021년 3월 9일)

9.9.0 GA 릴리즈는 AWS, Azure 및 Google Cloud Platform에서 사용할 수 있습니다. 이 릴리즈에는 다음과 같은 새로운 기능과 향상된 기능이 포함되어 있습니다.



=== 쓰기 성능 향상

이 릴리즈에는 모든 클라우드 공급자와 모든 구성에서 Cloud Volumes ONTAP의 쓰기 성능이 향상되었습니다.



=== 새로운 EC2 인스턴스 유형 지원

이제 Cloud Volumes ONTAP는 다음과 같은 Amazon EC2 인스턴스 유형에서 지원됩니다.

* 표준 및 BYOL의 m5a.2xLarge
* m5a.16xLarge, 프리미엄 및 BYOL
* C5A.12xLarge, 프리미엄 및 BYOL


에 대해 자세히 알아보십시오 https://aws.amazon.com/ec2/instance-types/m5/["M5a 인스턴스"^] 및 https://aws.amazon.com/ec2/instance-types/c5/["C5A 인스턴스"^].

link:reference-configs-aws.html["AWS에서 지원되는 구성을 봅니다"].



=== Azure에서 24개의 스토리지 VM 지원

BYOL(Bring Your Own License) 방식으로 Azure에서 24개의 스토리지 VM이 Cloud Volumes ONTAP에서 지원됩니다. 여기에는 DR에 사용되는 최대 12개의 스토리지 VM이 포함됩니다.

기본적으로 Cloud Volumes ONTAP와 함께 제공되는 첫 번째 스토리지 VM 외에 각 additional_data-serving_storage VM에 대해 애드온 라이센스가 필요합니다. SVM 애드온 라이센스를 받으려면 어카운트 팀에 문의하십시오.

DR(재해 복구)에 대해 구성하는 스토리지 VM에는 추가 라이센스(무료)가 필요하지 않지만 스토리지 VM 제한에 대해 카운트됩니다.

link:reference-limits-azure.html#storage-vm-limits["Azure의 스토리지 VM 제한에 대해 자세히 알아보십시오"].

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-azure.html["Azure에서 Cloud Volumes ONTAP용 데이터 서비스 스토리지 VM을 생성하는 방법에 대해 알아보십시오"^].



== BlueXP 커넥터의 필수 버전입니다

새 Cloud Volumes ONTAP 9.9.0 시스템을 배포하고 기존 시스템을 9.9.0으로 업그레이드하려면 BlueXP Connector가 버전 3.9.4 이상을 실행해야 합니다.



== 커넥터 버전 3.9.4에 도입된 변경 사항

Connector 3.9.4 릴리스에는 AWS KMS 지원에 대한 향상된 기능, Google Cloud의 공유 VPC 지원, Google Cloud의 IP 감소 등 Cloud Volumes ONTAP 관리를 위한 몇 가지 향상된 기능이 포함되어 있습니다.

로 이동합니다 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["BlueXP 릴리스 정보"^] 3.9.4 릴리스에 대한 자세한 내용은 을 참조하십시오.



== 노트 업그레이드

* Cloud Volumes ONTAP 업그레이드는 BlueXP에서 완료해야 합니다. System Manager 또는 CLI를 사용하여 Cloud Volumes ONTAP를 업그레이드해서는 안 됩니다. 이렇게 하면 시스템 안정성에 영향을 줄 수 있습니다.
* 9.8 릴리즈에서 Cloud Volumes ONTAP 9.0으로 업그레이드할 수 있습니다. BlueXP는 기존 Cloud Volumes ONTAP 9.8 시스템을 9.9.0 릴리즈로 업그레이드하라는 메시지를 표시합니다.
+
http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["BlueXP에서 알림을 받을 때 업그레이드하는 방법에 대해 알아봅니다"^].

* 단일 노드 시스템을 업그레이드하면 시스템이 최대 25분 동안 오프라인 상태로 전환되고 이 동안 I/O가 중단됩니다.
* HA 2노드 업그레이드는 무중단으로 I/O를 업그레이드할 수 있으며 이 무중단 업그레이드 프로세스 중에 각 노드가 동시 업그레이드되어 클라이언트에 I/O를 계속 제공합니다.
* AWS에서는 새로운 Cloud Volumes ONTAP 구축에서 C4, M4 및 R4 EC2 인스턴스 유형이 더 이상 지원되지 않습니다. C4, M4 또는 R4 인스턴스 유형에서 실행 중인 기존 시스템이 있는 경우 C5, M5 또는 R5 인스턴스 제품군의 인스턴스 유형으로 변경해야 합니다. 인스턴스 유형을 변경할 수 없는 경우 업그레이드하기 전에 향상된 네트워킹을 활성화해야 합니다.
+
link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html#upgrades-in-aws-with-c4-m4-and-r4-ec2-instance-types["AWS에서 C4, M4 및 R4 EC2 인스턴스 유형으로 업그레이드하는 방법을 알아보십시오."]
link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-change-ec2-instance.html["Cloud Volumes ONTAP의 EC2 인스턴스 유형을 변경하는 방법에 대해 알아보십시오"^].

+
을 참조하십시오 link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["NetApp 지원"^] 이러한 인스턴스 유형의 가용성 및 지원에 대한 자세한 내용을 보려면 를 참조하십시오.


